###
# Get all notes
GET http://localhost:3001/api/notes
Content-Type: application/json

###
# Create a new note
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "This is a sample note created using the REST client extension for Visual Studio Code.",
  "important": true
}